//MIME-Types
export const contentTypesByExtension = {
  '3gp':  'video/3gpp	',
  '3g2':  'video/3gpp2',
  '7z':   'application/x-7z-compressed',
  'pdf':  'application/pdf',
  'aac':  'audio/x-aac',
  'apk':  'application/vnd.android.package-archive',
  'dmg':  'application/x-apple-diskimage',
  's':    'text/x-asm',
  'avi':  'video/x-msvideo',
  'bin':  'application/octet-stream',
  'bmp':  'image/bmp',
  'sh':   'application/x-sh',
  'c':    'text/x-c',
  'css':  'text/css',
  'csv':  'text/csv',
  'dvi':  'application/x-dvi',
  'svc':  'application/vnd.dvb.service',
  'dtd':  'application/xml-dtd',
  'epub': 'application/epub+zip',
  'eml':  'message/rfc822',
  'gtar': 'application/x-gtar',
  'gif':  'image/gif',
  'h261': 'video/h261',
  'h263': 'video/h263',
  'h264': 'video/h264',
  'ics':  'text/calendar',
  'ico':  'image/x-icon',
  'cer':  'application/pkix-cert',
  'pki':  'application/pkixcmp',
  'crl':  'application/pkix-crl',
  'jar':  'application/java-archive',
  'class':'application/java-vm',
  'java': 'text/x-java-source,java',
  'js':   'text/javascript	',
  'json': 'application/json	',
  'jpeg': 'image/jpeg',
  'jpg':  'image/jpeg',
  'latex':'application/x-latex',
  'm4v':  'video/x-m4v',
  'exe':  'application/x-msdownload',
  'xls':  'application/vnd.ms-excel',
  'xltm': 'application/vnd.ms-excel.template.macroenabled.12',
  'xlsm': 'application/vnd.ms-excel.sheet.macroenabled.12',
  'pptx': 'application/vnd.openxmlformats-officedocument.presentationml.presentation',
  'ppsx': 'application/vnd.openxmlformats-officedocument.presentationml.slideshow',
  'potx': 'application/vnd.openxmlformats-officedocument.presentationml.template',
  'xlsx': 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
  'xltx': 'application/vnd.openxmlformats-officedocument.spreadsheetml.template',
  'docx': 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
  'dotx': 'application/vnd.openxmlformats-officedocument.wordprocessingml.template',
  'ppt':  'application/vnd.ms-powerpoint',
  'pptm': 'application/vnd.ms-powerpoint.presentation.macroenabled.12',
  'ppsm': 'application/vnd.ms-powerpoint.slideshow.macroenabled.12',
  'potm': 'application/vnd.ms-powerpoint.template.macroenabled.12',
  'mpp':  'application/vnd.ms-project',
  'vsd':  'application/vnd.visio',
  'vsdx': 'application/vnd.visio2013',
  'wma':  'audio/x-ms-wma',
  'wmv':  'video/x-ms-wmv',
  'doc':  'application/msword',
  'docm': 'application/vnd.ms-word.document.macroenabled.12',
  'dotm': 'application/vnd.ms-word.template.macroenabled.12',
  'mid':  'audio/midi',
  'mpga': 'audio/mpeg',
  'mpeg': 'video/mpeg',
  'mp4a': 'audio/mp4',
  'mp4':  'audio/mp4',
  'ogx':  'application/ogg',
  'oga':  'audio/ogg',
  'ogv':  'video/ogg',
  'weba': 'audio/webm',
  'webm': 'video/webm',
  'odp':  'application/vnd.oasis.opendocument.presentation',
  'otp':  'application/vnd.oasis.opendocument.presentation-template',
  'ods':  'application/vnd.oasis.opendocument.spreadsheet',
  'ots':  'application/vnd.oasis.opendocument.spreadsheet-template',
  'odt':  'application/vnd.oasis.opendocument.text	',
  'odm':  'odm',
  'ott':  'application/vnd.oasis.opendocument.text-template',
  'p':    'text/x-pascal',
  'png':  'image/png',
  'pgp':  'application/pgp-encrypted',
  'rar':  'application/x-rar-compressed',
  'rtf':  'application/rtf',
  'rtx':  'text/richtext',
  'svg':  'image/svg+xml',
  'sgml': 'text/sgml',
  'tar':  'application/x-tar',
  'tex':  'application/x-tex',
  'txt':  'text/plain',
  'uri':  'text/uri-list',
  'vcs':  'text/x-vcalendar',
  'wav':  'audio/x-wav',
  'wsdl': 'application/wsdl+xml',
  'der':  'application/x-x509-ca-cert',
  'xhtml':'application/xhtml+xml',
  'xml':  'application/xml',
  'xslt': 'application/xslt+xml',
  'yaml': 'text/yaml',
  'zip':  'application/zip',
  'html': 'text/html'
};